name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    name: Build Docker Image
    runs-on: ubuntu-18.04
    container: scoir/canis-build:latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        repository: canislabs/canis-test
