name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    name: Build Docker Image
    runs-on: ubuntu-18.04
    container: scoir/canis-build:latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make canis-docker
