name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  publish-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-18.04
    container: scoir/canis-build:latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=canislabs/canis-test
        VERSION=${GITHUB_REF#refs/tags/}

        TAGS="${DOCKER_IMAGE}:${VERSION}"
        if echo $VERSION | grep -Eq  '^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'; then
          MINOR=${VERSION%.*}
          MAJOR=${MINOR%.*}
          TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
        fi
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.prep.outputs.tags }}

  publish-helm-chart:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_dir: /canis-chart-test
        env:
          CR_TOKEN: "${{ secrets.ACCESS_TOKEN }}"